---
title: "SeqArray Overview"
author: "Dr. Xiuwen Zheng (Department of Biostatistics, University of Washington, Seattle)"
date: "JSM 2013 / Updated on Apr 20, 2016"
output: slidy_presentation
vignette: >
  %\VignetteIndexEntry{SeqArray Overview}
  %\VignetteDepends{gdsfmt}
  %\VignetteKeywords{GWAS, Whole-genome, Sequencing, SNV}
  %\VignetteEngine{knitr::rmarkdown}
---

## Introduction

Thousands of gigabyte genetic data sets provide significant challenges in data management, even on well-equipped hardware

- The 1000 Genomes Project Phase 1 (1KG): ~39 million variants (SNPs, indels and structural variants) of 1092 individuals (http://www.1000genomes.org)
- Variant Call Format (VCF) files: genotypes + annotation, totaling ~146.7GB in a compressed manner (gz files)


## Methods

**CoreArray (C++ library)**

- designed for large-scale data management of genome-wide variants
- data format (GDS) to store multiple array-oriented datasets in a single file

**Two R packages**

- gdsfmt -- R interface to CoreArray Genomic Data Structure (GDS) files
- SeqArray -- specifically designed for data management of genome-wide sequence variants from Variant Call Format (VCF) files


## Advantages

1. Direct access of data without parsing VCF text files

2. Stored in a binary and array-oriented manner
    - 2 bits are employed as a primitive type to store alleles (e.g., A, G, C, T)
    - efficient access of variants using R language

3. Genotypic data stored in a compressed manner
    - rare variants: highly compressed without sacrificing access efficiency
    - e.g., 1KG, 26G raw genotypes: 1.5G by the zlib algorithm (5.8%!)

4. Run in parallel!


## File Contents

```
File: SeqArray/extdata/CEU_Exon.gds (387.3K)
|--+ description   [  ] *
|--+ sample.id   { VStr8 90 ZIP_ra(30.8%), 222B }
|--+ variant.id   { Int32 1348 ZIP_ra(35.7%), 1.9K }
|--+ position   { Int32 1348 ZIP_ra(86.4%), 4.6K }
|--+ chromosome   { VStr8 1348 ZIP_ra(2.66%), 91B }
|--+ allele   { VStr8 1348 ZIP_ra(17.2%), 928B }
|--+ genotype   [  ] *
|  \--+ data   { Bit2 2x90x1348 ZIP_ra(28.4%), 16.8K } *
|--+ phase   [  ]
|  \--+ data   { Bit1 90x1348 ZIP_ra(0.36%), 55B } *
|--+ annotation   [  ]
|  |--+ id   { VStr8 1348 ZIP_ra(41.0%), 5.8K }
|  |--+ qual   { Float32 1348 ZIP_ra(0.91%), 49B }
|  |--+ filter   { Int32,factor 1348 ZIP_ra(0.89%), 48B } *
|  |--+ info   [  ]
|  |  |--+ AA   { VStr8 1348 ZIP_ra(24.2%), 653B } *
|  |  \--+ HM2   { Bit1 1348 ZIP_ra(117.2%), 198B } *
|  \--+ format   [  ]
|     \--+ DP   [  ] *
|        \--+ data   { Int32 90x1348 ZIP_ra(33.8%), 160.3K }
\--+ sample.annotation   [  ]
   \--+ family   { VStr8 90 ZIP_ra(34.7%), 135B }
```


## Key Functions

**Table 1**: The key functions in the SeqArray package.

| Function     | Description |
|:-------------|:-------------------------------------------|
| seqVCF2GDS   | Reformats VCF files to GDS format |
| seqSummary   | Gets the summary (# of samples, # of variants, INFO/FORMAT variables, etc) |
| seqSetFilter | Sets a filter to sample or variant (i.e., define a subset of data) |
| seqGetData   | Gets data from a SeqArray file (or a subset of data) |
| seqApply     | Applies a user-defined function over array margins |
| seqParallel  | Applies functions in parallel |


## Benchmark

**Dataset:**

- 1000 Genomes Project Phase 1, chromosome 1
- 3,007,196 variants, 1092 individuals
- the original VCF file: 10.7G (compressed)
    * genotypes (GT) + annotations (DS, genotype dosage; GL, genotype likelihoods)
- reformat to a single SeqArray file: 10.6G
    * genotype: bit2, ZIP (5.95%), 97.8 MB
- R: v3.2.0

**Calculate the frequencies of reference alleles**

1. R code (sequential version)
2. R code (parallel version)
3. Seamless R and C++ integration via the Rcpp package (sequential version)


## Benchmark -- Test 1 (sequentially)

```R
# load the R package
library(SeqArray)
# open the file
genofile <- seqOpen("1KG_chr1.gds")

# apply the user-defined function variant by variant
system.time(
    afreq <- seqApply(genofile, "genotype", as.is="double", margin="by.variant",
        FUN = function(x) { mean(x==0L, na.rm=TRUE) }))
```

**189.8 seconds** on a Linux system with two quad-core Intel processors (2.27GHz) and 32 GB RAM

`function(x) { mean(x==0L, na.rm=TRUE) }` is the user-defined function, where `x` looks like:

```R
                           sample
  allele [,1] [,2] [,3] [,4] [,5]
    [1,]    0    1    0   NA    1
    [2,]    0    0    0    1    0
```

0 -- reference allele, 1 -- the first alternative allele


## Benchmark -- Test 2 (in parallel)

`seqParallel()` splits genotypes into 4 non-overlapping parts according to different cores.

```R
# load the R package
library(parallel)

# create a computing cluster with 4 cores
seqParallelSetup(4)

# run in parallel
system.time(afreq <- seqParallel(gdsfile=genofile,
    FUN = function(f) {
        seqApply(f, "genotype", as.is="double", margin="by.variant",
            FUN = function(x) mean(x==0L, na.rm=TRUE))
    }, split = "by.variant")
)
```

**50.3 seconds** (vs 189.8s in Test 1)


## Benchmark -- Test 3 (C++ Integration)

```R
library(Rcpp)

# dynamically define an inline C/C++ function in R
cppFunction('double RefAlleleFreq(IntegerMatrix x) {
    int nrow = x.nrow(), ncol = x.ncol();
    int cnt=0, zero_cnt=0, g;
    for (int i = 0; i < nrow; i++) {
            for (int j = 0; j < ncol; j++) {
                if ((g = x(i, j)) != NA_INTEGER) {
                    cnt ++;
                    if (g == 0) zero_cnt ++;
                }
    }}
    return double(zero_cnt) / cnt;
}')

system.time(
    afreq <- seqApply(genofile, "genotype", RefAlleleFreq,
        as.is="double", margin="by.variant")
)
```

**33.9 seconds** (fastest! vs 189.8s in Test 1 and 50.3s in Test 2)


## Conclusion

**SeqArray will be of great interest to**

- R users involved in data analyses of large-scale sequence variants
- particularly those with limited experience of parallel / high-performance computing

**SeqVarTools (Bioconductor)**

- variant analysis, such like allele frequencies, HWE, Mendelian errors, etc
- functions to display genotypes / annotations in a readable format

**SNPRelate (Bioconductor)**

- a parallel computing toolset for relatedness and principal component analysis


## Resource

1000 Genomes Project:

1. Phase 1:
	- [1KG_autosomes_SHAPEIT2_integrated_phase1_v3_20101123_snps_indels_svs_genotypes.seq.gds](http://bochet.gcc.biostat.washington.edu/seqarray/1000genomes/1KG_autosomes_SHAPEIT2_integrated_phase1_v3_20101123_snps_indels_svs_genotypes.seq.gds)
	- 1,092 individuals and 38,219,238 variants [1.5G]

2. Phase 3:
	- [1KG_autosomes_phase3_shapeit2_mvncall_integrated_v5_20130502.seq.gds](http://bochet.gcc.biostat.washington.edu/seqarray/1000genomes/1KG_autosomes_phase3_shapeit2_mvncall_integrated_v5_20130502.seq.gds)
	- 2,504 individuals and 81,271,745 variants [5.2G]


## Acknowledgements

Department of Biostatistics at University of Washington -- Seattle, 

Genetic Analysis Center:

- Dr. Stephanie M. Gogarten
- Dr. David Levine
- Dr. Cathy Laurie
