#######################################################################
#
# Package Name: SeqArray
#
# Description: A list of units of selected variants
#


#######################################################################
# Get a list of units of selected variants via sliding windows based on basepairs
#
seqUnitSlidingWindows <- function(gdsfile, win.size=5000L, win.shift=2500L, win.start=0L,
    verbose=TRUE)
{
    stopifnot(inherits(gdsfile, "SeqVarGDSClass"))
    stopifnot(is.numeric(win.size), is.finite(win.size), length(win.size)==1L,
        win.size>0L)
    stopifnot(is.numeric(win.shift), is.finite(win.shift), length(win.shift)==1L,
        win.shift>0L)

    # save state
    seqSetFilter(gdsfile, action="push", verbose=FALSE)
    on.exit({ seqSetFilter(gdsfile, action="pop", verbose=FALSE) })

    # chromosome list
    chrlst <- unique(seqGetData(gdsfile, "chromosome"))
    if (length(chrlst) <= 0L) stop("No selected variant!")
    ans <- NULL
    for (chr in chrlst)
    {
        cat("Chromosome: ", chr, "\n", sep="")
        seqSetFilterChrom(gdsfile, include=chr, verbose=verbose)
        idx <- which(seqGetFilter(gdsfile)$variant.sel)
        pos <- seqGetData(gdsfile, "position")
        if (!is.unsorted(pos) || pos[1L]>pos[length(pos)])
        {
            i <- order(pos)
            pos <- pos[i]; idx <- idx[i]
        }
        # generated by sliding windows
        rv <- .Call(SEQ_Unit_SlidingWindows, pos, idx, win.size, win.shift, win.start,
            integer(length(pos)))
        ans <- c(ans, rv)
        # 
        seqSetFilter(gdsfile, action="pop", verbose=FALSE)
        seqSetFilter(gdsfile, action="push", verbose=FALSE)
    }

    # output
    class(ans) <- "SeqUnitListClass"
    ans
}
